a: a.c
	gcc -ggdb3 a.c -o a
b: b.c
	gcc -ggdb3 b.c -o b
b-smartish: b-smartish.c
	gcc -ggdb3 b-smartish.c -o b-smartish
b-smartish-opt: b-smartish.c
	gcc -O3 -march=native b-smartish.c -o b-smartish-opt
